AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Amplify App with CloudFormation Stack

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: YourNextjsApp
      Repository: 
        RepositoryUrl: https://github.com/yourusername/your-nextjs-repo.git
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - npm ci
                - npm run build
          artifacts:
            baseDirectory: ./
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        EnablePullRequestPreview: false
      AccessToken: !Ref AmplifyToken

  AmplifyToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AmplifyToken
      Description: GitHub Token for Amplify
      GenerateSecretString:
        SecretStringTemplate: '{"accessToken": ""}'
        GenerateStringKey: "accessToken"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - amplify:*
                Resource: '*'

  CloudFormationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cloudformation-templates-us-east-1/YourTemplate.yaml"
      RoleARN: !GetAtt CloudFormationDeploymentRole.Arn
