AWSTemplateFormatVersion: '2024-09-08'
Description: AWS Amplify App with CloudFormation Stack

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: test_next_app
      Repository: 'https://github.com/MFaad1/test_Next_App'
      AccessToken: '{{resolve:secretsmanager:github:SecretString:github_pat}}'
      IAMServiceRole: 'arn:aws:iam::502534243523:role/service-role/AmplifySSRLoggingRole-dl9wnpuigxyq6'
      Platform: WEB_COMPUTE
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - npm ci
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true

  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmplifyFullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - amplify:*
                Resource: '*'
