Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: YourNextjsApp
      Repository: 
        RepositoryUrl: https://github.com/MFaad1/test_Next_App.git
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - npm ci
                - npm run build
          artifacts:
            baseDirectory: ./
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        EnablePullRequestPreview: false
      AccessToken: !Ref AmplifyToken

  AmplifyToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AmplifyToken
      Description: GitHub Token for Amplify
      GenerateSecretString:
        SecretStringTemplate: '{"accessToken": ""}'
        GenerateStringKey: "accessToken"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
