name: Deploy Next.js App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn run build

      - name: Configure AWS Region
        run: aws configure set region us-east-1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Check if CloudFormation stack exists and if it's in ROLLBACK_COMPLETE state
      - name: Check CloudFormation stack status
        id: check-stack
        run: |
          status=$(aws cloudformation describe-stacks --stack-name NextJsAppStack --region us-east-1 --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "NON_EXISTENT")
          echo "::set-output name=status::$status"
          
      # Deploy or create CloudFormation stack
      - name: Deploy or create CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yaml \
            --stack-name NextJsAppStack \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --region us-east-1
