name: Deploy Next.js App
run-name: Deploy commit ${{ github.sha }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - dev
jobs:
  cloudformation_deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Package Lambda Function Code
        run: aws cloudformation package --template-file ./cloudformation-template.yaml --s3-bucket my-s3-bucket-name --region us-east-1
