Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: YourNextjsApp
      Repository: 
        RepositoryUrl: https://github.com/MFaad1/test_Next_App.git
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - npm ci
                - npm run build
          artifacts:
            baseDirectory: ./
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        EnablePullRequestPreview: false
      AccessToken: !Ref AmplifyToken

  AmplifyToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AmplifyToken
      Description: GitHub Token for Amplify
      GenerateSecretString:
        SecretStringTemplate: '{"accessToken": ""}'
        GenerateStringKey: "accessToken"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --template-file cloudformation-template.yaml --stack-name NextJsAppStack --region eu-north-1