name: Deploy to AWS Amplify

on:
  push:
    branches:
      - pr-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

    - name: Verify Amplify CLI Installation
      run: amplify --version

 

    - name: Initialize Amplify
      run: |
        mkdir amplify-temp
        cd amplify-temp
        amplify init --app https://github.com/MFaad1/test_Next_App --amplifyBranchName pr-main --yes
        cd ..
        rm -rf amplify-temp

    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli    

    - name: Build Next.js App
      run: npm run build

    - name: Deploy to AWS Amplify
      run: amplify publish --simple
