name: Deploy Next.js App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn run build

      - name: Configure AWS Region
        run: aws configure set region us-east-1

      - name: Describe CloudFormation stack events
        run: |
          aws cloudformation describe-stack-events --stack-name NextJsAppStack --region us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yaml \
            --stack-name NextJsAppStack \
            --region us-east-1 \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
