name: Deploy Next.js App
run-name: Deploy commit ${{ github.sha }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'ext_resources/**'
      - '!ext_resources/containers/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
   cloudformation_deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
       - name: Package Lambda Function Code
        run: aws cloudformation package --template-file duckstack-dev.yaml --output-template-file duckstack_packaged.yaml --region us-east-1
 